services:
  - type: web
    name: kho-truyen-full-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: 8787
      - key: TRUST_PROXY
        value: "1"
    disk:
      name: kho-truyen-data
      mountPath: /app/server
      sizeGB: 1
