const http=require('http'),fs=require('fs'),path=require('path'),url=require('url'),zlib=require('zlib'),crypto=require('crypto');
const {DatabaseSync}=require('node:sqlite');
const {hash,token}=require('./auth');
const ROOT=path.resolve(__dirname,'..'),DATA_DIR=__dirname,DB_FILE=path.join(DATA_DIR,'kho_truyen.sqlite'),SCHEMA_FILE=path.join(DATA_DIR,'schema.sql'),COVERS=path.join(DATA_DIR,'covers'),PORT=Number(process.env.PORT||8787),SESSION_DAYS=30;
fs.mkdirSync(COVERS,{recursive:true});
const db=new DatabaseSync(DB_FILE); db.exec(fs.readFileSync(SCHEMA_FILE,'utf8')); db.exec('PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA temp_store=MEMORY; PRAGMA cache_size=-20000; PRAGMA foreign_keys=ON;');
const now=()=>new Date().toISOString();
const CACHE_TTL=Number(process.env.KHO_CACHE_TTL_MS||5000), CACHE=new Map(), INFLIGHT=new Map();
const RATE=new Map();
function cacheKey(req){return req.method+' '+req.url}
function cacheGet(key){const x=CACHE.get(key);if(!x)return null;if(x.expires<Date.now()){CACHE.delete(key);return null}return x.data}
function cacheSet(key,data){CACHE.set(key,{data,expires:Date.now()+CACHE_TTL});if(CACHE.size>5000){const first=CACHE.keys().next().value;if(first)CACHE.delete(first)}}
function cacheClear(prefix=''){for(const k of CACHE.keys())if(!prefix||k.includes(prefix))CACHE.delete(k)}
function rateLimit(req,res,group,limit,windowMs=60000){const ip=(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim(),key=group+'|'+ip,nowMs=Date.now();if(RATE.size>2000){for(const [k,v] of RATE)if(v.reset<=nowMs)RATE.delete(k)}let x=RATE.get(key);if(!x||x.reset<=nowMs)x={count:0,reset:nowMs+windowMs};x.count++;RATE.set(key,x);if(x.count>limit){const retry=Math.ceil((x.reset-nowMs)/1000);send(res,429,{error:'RATE_LIMITED',retryAfter:retry});return false}return true}
function etag(data){return '"'+crypto.createHash('sha1').update(data).digest('hex')+'"'}
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const q=(sql,...a)=>db.prepare(sql).get(...a); const all=(sql,...a)=>db.prepare(sql).all(...a); const run=(sql,...a)=>db.prepare(sql).run(...a);
try{db.exec("ALTER TABLE chapters ADD COLUMN search_key TEXT DEFAULT ''");}catch{}
for(const r of all('SELECT id,title FROM chapters WHERE search_key="" OR search_key IS NULL'))run('UPDATE chapters SET search_key=? WHERE id=?',norm(r.title),r.id);
db.exec('CREATE INDEX IF NOT EXISTS idx_chapters_search ON chapters(story_id,search_key);');
function seed(){if(q('SELECT 1 AS x FROM stories LIMIT 1'))return;const legacy=path.join(DATA_DIR,'seed.json');if(!fs.existsSync(legacy))return;const d=JSON.parse(fs.readFileSync(legacy,'utf8'));const t=now();for(const b of d.books||[]){run('INSERT INTO stories(id,title,author,category,description,search_key,tone,status,cover_path,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',b.id,b.title,b.author||'',b.cat||'Khác',b.desc||'',norm([b.title,b.author,b.cat,b.desc].join(' ')),b.tone||'', 'FULL','',t,t);(b.chapters||[]).forEach((c,i)=>run('INSERT INTO chapters(id,story_id,chapter_index,title,content,created_at,updated_at,search_key) VALUES(?,?,?,?,?,?,?,?)',`${b.id}:${i}`,b.id,i,c[0]||`Chương ${i+1}`,c[1]||'',t,t,norm(c[0]||`Chương ${i+1}`)));} }
seed();
function send(res,status,data,type='application/json; charset=utf-8',req=null){
  const raw=type.startsWith('application/json')?JSON.stringify(data):Buffer.isBuffer(data)?data:Buffer.from(String(data));
  const bodyBuf=Buffer.isBuffer(raw)?raw:Buffer.from(raw); const tag=etag(bodyBuf); const headers={'Content-Type':type,'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization, If-None-Match','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','ETag':tag,'Vary':'Accept-Encoding','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'};
  if(req&&req.method==='GET'&&req.headers['if-none-match']===tag){headers['Cache-Control']='private, max-age=5';res.writeHead(304,headers);return res.end()}
  if(req&&req.method==='GET')headers['Cache-Control']='private, max-age=5';
  const canGzip=req&&/gzip/i.test(req.headers['accept-encoding']||'')&&bodyBuf.length>=512&&status!==204;
  if(canGzip){headers['Content-Encoding']='gzip';zlib.gzip(bodyBuf,(e,b)=>{if(e){res.writeHead(status,headers);return res.end(bodyBuf)}headers['Content-Length']=b.length;res.writeHead(status,headers);res.end(b)})}
  else {headers['Content-Length']=bodyBuf.length;res.writeHead(status,headers);res.end(bodyBuf)}
}
function body(req,limit=10*1024*1024){return new Promise((resolve,reject)=>{let s='',n=0;req.on('data',c=>{n+=c.length;if(n>limit){reject(new Error('BODY_TOO_LARGE'));req.destroy();return}s+=c});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(new Error('BAD_JSON'))}});req.on('error',reject)})}
function userByToken(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const s=q('SELECT * FROM sessions WHERE token=? AND expires_at>?',h.slice(7),now());if(!s)return null;return q('SELECT id,username,display_name,role,created_at FROM users WHERE id=?',s.user_id)||null}
function requireUser(req,res){const u=userByToken(req);if(!u){send(res,401,{error:'UNAUTHORIZED'});return null}return u}
function requireAdmin(req,res){const u=requireUser(req,res);if(!u)return null;if(u.role!=='admin'){send(res,403,{error:'ADMIN_REQUIRED'});return null}return u}
function publicUser(u){return {id:u.id,username:u.username,displayName:u.display_name||u.username,role:u.role||'user',createdAt:u.created_at}}
function storyRow(r){return {id:r.id,title:r.title,author:r.author,cat:r.category,desc:r.description,tone:r.tone,status:r.status,cover:r.cover_path||'',chapters:Number(r.chapters||0),createdAt:r.created_at,updatedAt:r.updated_at}}
function getStory(id){return q(`SELECT s.*,COUNT(c.id) chapters FROM stories s LEFT JOIN chapters c ON c.story_id=s.id WHERE s.id=? GROUP BY s.id`,id)}
function chapterRow(r){return {bookId:r.story_id,index:Number(r.chapter_index),title:r.title,content:r.content,id:r.id,updatedAt:r.updated_at}}
function route(req,res){const reply=(status,data,type='application/json; charset=utf-8')=>send(res,status,data,type,req); if(req.method==='OPTIONS')return reply(204,'');const u=url.parse(req.url,true),p=u.pathname.replace(/\/+$/,'')||'/';
if(p==='/api/v1/auth/login'||p==='/api/v1/auth/register'){if(!rateLimit(req,res,'auth',60))return;}
if(p.startsWith('/api/v1/admin/')){if(!rateLimit(req,res,'admin',180))return;}
if(p==='/api/v1/health')return reply(200,{ok:true,version:'1.7.0',database:'sqlite',books:Number(q('SELECT COUNT(*) n FROM stories').n),chapters:Number(q('SELECT COUNT(*) n FROM chapters').n),users:Number(q('SELECT COUNT(*) n FROM users').n)});
if(p==='/api/v1/auth/register'&&req.method==='POST')return body(req).then(x=>{const username=String(x.username||'').trim().toLowerCase(),password=String(x.password||'');if(!/^[a-z0-9_.-]{3,32}$/.test(username)||password.length<6)return reply(400,{error:'INVALID_ACCOUNT'});if(q('SELECT 1 FROM users WHERE username=?',username))return reply(409,{error:'USERNAME_EXISTS'});const id='u_'+token().slice(0,12),h=hash(password),t=now(),role=Number(q('SELECT COUNT(*) n FROM users').n)===0?'admin':'user';run('INSERT INTO users VALUES(?,?,?,?,?,?,?)',id,username,h.hash,h.salt,String(x.displayName||username).slice(0,60),role,t);run('INSERT INTO profiles VALUES(?,?,?)',id,'',t);const sess=token();run('INSERT INTO sessions VALUES(?,?,?,?)',sess,id,new Date(Date.now()+SESSION_DAYS*864e5).toISOString(),t);const u=q('SELECT * FROM users WHERE id=?',id);reply(201,{token:sess,user:publicUser(u)})}).catch(e=>reply(e.message==='BODY_TOO_LARGE'?413:400,{error:e.message||'BAD_JSON'}));
if(p==='/api/v1/auth/login'&&req.method==='POST')return body(req).then(x=>{const u=q('SELECT * FROM users WHERE username=?',String(x.username||'').trim().toLowerCase());if(!u)return reply(401,{error:'INVALID_CREDENTIALS'});if(hash(String(x.password||''),u.password_salt).hash!==u.password_hash)return reply(401,{error:'INVALID_CREDENTIALS'});const sess=token(),t=now();run('INSERT INTO sessions VALUES(?,?,?,?)',sess,u.id,new Date(Date.now()+SESSION_DAYS*864e5).toISOString(),t);reply(200,{token:sess,user:publicUser(u)})}).catch(()=>reply(400,{error:'BAD_JSON'}));
if(p==='/api/v1/auth/me'&&req.method==='GET'){const u=userByToken(req);return u?reply(200,publicUser(u)):reply(401,{error:'UNAUTHORIZED'})}
if(p==='/api/v1/auth/logout'&&req.method==='POST'){const h=(req.headers.authorization||'').replace(/^Bearer /,'');if(h)run('DELETE FROM sessions WHERE token=?',h);cacheClear('/api/v1/stories');return reply(200,{ok:true})}
if(p==='/api/v1/profile'&&req.method==='GET'){const u=requireUser(req,res);if(!u)return;const p0=q('SELECT avatar,updated_at updatedAt FROM profiles WHERE user_id=?',u.id);return reply(200,{displayName:u.display_name||u.username,avatar:p0?.avatar||'',updatedAt:p0?.updatedAt||u.created_at})}
if(p==='/api/v1/profile'&&req.method==='PUT')return body(req).then(x=>{const u=requireUser(req,res);if(!u)return;const t=now(),name=String(x.displayName||u.username).slice(0,60),avatar=String(x.avatar||'').slice(0,500);run('UPDATE users SET display_name=? WHERE id=?',name,u.id);run('INSERT INTO profiles(user_id,avatar,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET avatar=excluded.avatar,updated_at=excluded.updated_at',u.id,avatar,t);reply(200,{displayName:name,avatar,updatedAt:t})}).catch(()=>reply(400,{error:'BAD_JSON'}));
if(p==='/api/v1/sync'&&req.method==='GET'){const u=requireUser(req,res);if(!u)return;const progress={},history={};for(const r of all('SELECT story_id,chapter_index,position,updated_at FROM reading_progress WHERE user_id=?',u.id))progress[r.story_id]={chapterIndex:r.chapter_index,position:r.position,updatedAt:r.updated_at};for(const r of all('SELECT story_id,chapter_index,position,updated_at FROM reading_history WHERE user_id=?',u.id))history[r.story_id]={chapterIndex:r.chapter_index,position:r.position,updatedAt:r.updated_at};return reply(200,{progress,history,favorites:all('SELECT story_id FROM favorites WHERE user_id=? ORDER BY created_at DESC',u.id).map(r=>r.story_id)})}
if(p==='/api/v1/progress'&&req.method==='PUT')return body(req).then(x=>{const u=requireUser(req,res);if(!u)return;const s=getStory(String(x.storyId||''));if(!s)return reply(400,{error:'INVALID_STORY'});const i=Math.max(0,Number(x.chapterIndex||0)),pos=Math.max(0,Number(x.position||0)),t=now();run('INSERT INTO reading_progress VALUES(?,?,?,?,?) ON CONFLICT(user_id,story_id) DO UPDATE SET chapter_index=excluded.chapter_index,position=excluded.position,updated_at=excluded.updated_at',u.id,s.id,i,pos,t);run('INSERT INTO reading_history VALUES(?,?,?,?,?) ON CONFLICT(user_id,story_id) DO UPDATE SET chapter_index=excluded.chapter_index,position=excluded.position,updated_at=excluded.updated_at',u.id,s.id,i,pos,t);reply(200,{chapterIndex:i,position:pos,updatedAt:t})}).catch(()=>reply(400,{error:'BAD_JSON'}));
if(p==='/api/v1/progress'&&req.method==='GET'){const u=requireUser(req,res);if(!u)return;const out={};for(const r of all('SELECT story_id,chapter_index,position,updated_at FROM reading_progress WHERE user_id=?',u.id))out[r.story_id]={chapterIndex:r.chapter_index,position:r.position,updatedAt:r.updated_at};return reply(200,out)}
if(p==='/api/v1/favorites'&&req.method==='GET'){const u=requireUser(req,res);if(!u)return;return reply(200,all('SELECT story_id FROM favorites WHERE user_id=? ORDER BY created_at DESC',u.id).map(r=>r.story_id))}
if(p==='/api/v1/favorites'&&req.method==='PUT')return body(req).then(x=>{const u=requireUser(req,res);if(!u)return;const s=getStory(String(x.storyId||''));if(!s)return reply(400,{error:'INVALID_STORY'});if(x.active===false)run('DELETE FROM favorites WHERE user_id=? AND story_id=?',u.id,s.id);else run('INSERT OR IGNORE INTO favorites VALUES(?,?,?)',u.id,s.id,now());reply(200,{items:all('SELECT story_id FROM favorites WHERE user_id=? ORDER BY created_at DESC',u.id).map(r=>r.story_id)})}).catch(()=>reply(400,{error:'BAD_JSON'}));
let m=p.match(/^\/api\/v1\/stories\/([^/]+)\/chapters\/(\d+)$/);if(m&&req.method==='GET'){const ck=cacheKey(req),hit=cacheGet(ck);if(hit)return reply(200,hit);const r=q('SELECT * FROM chapters WHERE story_id=? AND chapter_index=?',m[1],Number(m[2]));if(!r)return reply(404,{error:'CHAPTER_NOT_FOUND'});const out=chapterRow(r);cacheSet(ck,out);return reply(200,out)}
m=p.match(/^\/api\/v1\/stories\/([^/]+)\/chapters$/);if(m&&req.method==='GET'){const ck=cacheKey(req),hit=cacheGet(ck);if(hit)return reply(200,hit);if(!getStory(m[1]))return reply(404,{error:'BOOK_NOT_FOUND'});const total=Number(q('SELECT COUNT(*) n FROM chapters WHERE story_id=?',m[1]).n);const hasPaging=u.query.page!=null||u.query.pageSize!=null||u.query.q!=null;const cq=String(u.query.q||'').trim();if(!hasPaging)return reply(200,all('SELECT id,story_id,chapter_index,title,updated_at FROM chapters WHERE story_id=? ORDER BY chapter_index',m[1]).map(chapterRow));const page=Math.max(1,Number(u.query.page||1)),size=Math.max(1,Math.min(100,Number(u.query.pageSize||50)));let rows;if(cq){const needle=norm(cq),like='%'+needle+'%',offset=(page-1)*size;
         const num=Number(cq); let countRow,filtered;
         if(Number.isFinite(num)&&String(num)===cq){
           countRow=q('SELECT COUNT(*) n FROM chapters WHERE story_id=? AND (search_key LIKE ? OR chapter_index=?)',m[1],like,num-1);
           filtered=all('SELECT id,story_id,chapter_index,title,updated_at FROM chapters WHERE story_id=? AND (search_key LIKE ? OR chapter_index=?) ORDER BY chapter_index LIMIT ? OFFSET ?',m[1],like,num-1,size,offset);
         }else{
           countRow=q('SELECT COUNT(*) n FROM chapters WHERE story_id=? AND search_key LIKE ?',m[1],like);
           filtered=all('SELECT id,story_id,chapter_index,title,updated_at FROM chapters WHERE story_id=? AND search_key LIKE ? ORDER BY chapter_index LIMIT ? OFFSET ?',m[1],like,size,offset);
         }
         const count=Number(countRow.n||0);
         return reply(200,{items:filtered.map(chapterRow),page,pageSize:size,total:Math.ceil(count/size),count})}else rows=all('SELECT id,story_id,chapter_index,title,updated_at FROM chapters WHERE story_id=? ORDER BY chapter_index LIMIT ? OFFSET ?',m[1],size,(page-1)*size);return reply(200,{items:rows.map(chapterRow),page,pageSize:size,total:Math.ceil(total/size),count:total})}
m=p.match(/^\/api\/v1\/stories\/([^/]+)$/);if(m&&req.method==='GET'){const ck=cacheKey(req),hit=cacheGet(ck);if(hit)return reply(200,hit);const s=getStory(m[1]);if(!s)return reply(404,{error:'BOOK_NOT_FOUND'});const out=storyRow(s);cacheSet(ck,out);return reply(200,out)}
if(p==='/api/v1/stories'&&req.method==='GET'){const ck=cacheKey(req),hit=cacheGet(ck);if(hit)return reply(200,hit);let where=[],args=[],sql=`SELECT s.*,COUNT(c.id) chapters FROM stories s LEFT JOIN chapters c ON c.story_id=s.id`;const qv=String(u.query.q||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(qv){where.push(`s.search_key LIKE ?`);const z='%'+norm(qv)+'%';args.push(z)}if(u.query.author&&u.query.author!=='all'){where.push('s.author=?');args.push(String(u.query.author))}if(u.query.category&&u.query.category!=='all'){where.push('s.category=?');args.push(String(u.query.category))}if(u.query.status&&u.query.status!=='all'){where.push('s.status=?');args.push(String(u.query.status).toUpperCase())}if(where.length)sql+=' WHERE '+where.join(' AND ');sql+=' GROUP BY s.id';const sort=u.query.sort||'title';sql+=' ORDER BY '+(sort==='chapters'?'chapters DESC':sort==='author'?'s.author COLLATE NOCASE':sort==='new'?'s.updated_at DESC':'s.title COLLATE NOCASE');const page=Math.max(1,Number(u.query.page||1)),size=Math.max(1,Math.min(100,Number(u.query.pageSize||12)));const total=Number(q('SELECT COUNT(*) n FROM ('+sql+')',...args).n),pagedSql=sql+' LIMIT ? OFFSET ?',paged=all(pagedSql,...args,size,(page-1)*size),items=paged.map(storyRow);const out={items,page,total:Math.max(1,Math.ceil(total/size)),pageSize:size,count:total};cacheSet(ck,out);return reply(200,out)}
if(p.startsWith('/api/v1/admin/')){const u0=requireAdmin(req,res);if(!u0)return;
 if(p==='/api/v1/admin/stats')return reply(200,{users:Number(q('SELECT COUNT(*) n FROM users').n),stories:Number(q('SELECT COUNT(*) n FROM stories').n),chapters:Number(q('SELECT COUNT(*) n FROM chapters').n),sessions:Number(q('SELECT COUNT(*) n FROM sessions').n),favorites:Number(q('SELECT COUNT(*) n FROM favorites').n)});
 if(p==='/api/v1/admin/stories'&&req.method==='GET')return reply(200,all(`SELECT s.*,COUNT(c.id) chapters FROM stories s LEFT JOIN chapters c ON c.story_id=s.id GROUP BY s.id ORDER BY s.updated_at DESC`).map(storyRow));
 if(p==='/api/v1/admin/stories'&&req.method==='POST')return body(req).then(x=>{const id='b_'+token().slice(0,8),t=now();const title=String(x.title||'Truyện mới').slice(0,200),author=String(x.author||'').slice(0,120),cat=String(x.cat||'Khác').slice(0,80),desc=String(x.desc||'').slice(0,2000),tone=String(x.tone||'').slice(0,200);run('INSERT INTO stories VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,title,author,cat,desc,norm([title,author,cat,desc].join(' ')),tone,'FULL','',t,t);cacheClear('/api/v1/stories');reply(201,storyRow(getStory(id)))});
 if(p==='/api/v1/admin/stories/bulk'&&req.method==='PUT')return body(req).then(x=>{
  const ids=Array.isArray(x.storyIds)?x.storyIds:Array.isArray(x.ids)?x.ids:[]; if(!ids.length)return reply(400,{error:'NO_STORIES'});
  const t=now(); let n=0; db.exec('BEGIN'); try{for(const id of ids){if(x.category!=null){run('UPDATE stories SET category=?,search_key=?,updated_at=? WHERE id=?',String(x.category).slice(0,80),norm([getStory(id)?.title||'',getStory(id)?.author||'',x.category,getStory(id)?.description||''].join(' ')),t,id);n++} if(x.status!=null){run('UPDATE stories SET status=?,updated_at=? WHERE id=?',String(x.status).slice(0,30),t,id);n++}} db.exec('COMMIT');cacheClear('/api/v1/stories');reply(200,{ok:true,updated:n})}catch(e){db.exec('ROLLBACK');reply(400,{error:'BULK_UPDATE_FAILED',detail:e.message})}
}).catch(()=>reply(400,{error:'BAD_JSON'}));
 m=p.match(/^\/api\/v1\/admin\/stories\/([^/]+)$/);if(m&&req.method==='PUT')return body(req).then(x=>{const s=getStory(m[1]);if(!s)return reply(404,{error:'BOOK_NOT_FOUND'});const t=now();const title=String(x.title??s.title).slice(0,200),author=String(x.author??s.author).slice(0,120),cat=String(x.cat??s.category).slice(0,80),desc=String(x.desc??s.description).slice(0,2000),tone=String(x.tone??s.tone).slice(0,200);run('UPDATE stories SET title=?,author=?,category=?,description=?,search_key=?,tone=?,updated_at=? WHERE id=?',title,author,cat,desc,norm([title,author,cat,desc].join(' ')),tone,t,s.id);cacheClear('/api/v1/stories');reply(200,storyRow(getStory(s.id)))});
 if(m&&req.method==='DELETE'){const sid=m[1];if(!getStory(sid))return reply(404,{error:'BOOK_NOT_FOUND'});db.exec('BEGIN');try{run('DELETE FROM favorites WHERE story_id=?',sid);run('DELETE FROM reading_history WHERE story_id=?',sid);run('DELETE FROM reading_progress WHERE story_id=?',sid);run('DELETE FROM chapters WHERE story_id=?',sid);run('DELETE FROM stories WHERE id=?',sid);db.exec('COMMIT');for(const f of fs.readdirSync(COVERS).filter(f=>f.startsWith(sid+'.')))try{fs.unlinkSync(path.join(COVERS,f))}catch{}cacheClear('/api/v1/stories');return reply(200,{ok:true})}catch(e){try{db.exec('ROLLBACK')}catch{};return reply(400,{error:'DELETE_STORY_FAILED',detail:e.message})}}
 m=p.match(/^\/api\/v1\/admin\/stories\/([^/]+)\/chapters$/);if(m&&req.method==='POST')return body(req).then(x=>{const s=getStory(m[1]);if(!s)return reply(404,{error:'BOOK_NOT_FOUND'});const i=x.index==null?Number(q('SELECT COALESCE(MAX(chapter_index),-1)+1 n FROM chapters WHERE story_id=?',s.id).n):Number(x.index);if(q('SELECT 1 FROM chapters WHERE story_id=? AND chapter_index=?',s.id,i))return reply(409,{error:'CHAPTER_EXISTS'});const id=`${s.id}:${i}`,t=now();run('INSERT INTO chapters(id,story_id,chapter_index,title,content,created_at,updated_at,search_key) VALUES(?,?,?,?,?,?,?,?)',id,s.id,i,String(x.title||`Chương ${i+1}`).slice(0,200),String(x.content||''),t,t,norm(String(x.title||`Chương ${i+1}`)));run('UPDATE stories SET updated_at=? WHERE id=?',t,s.id);cacheClear('/api/v1/stories');reply(201,chapterRow(q('SELECT * FROM chapters WHERE id=?',id)))});
 m=p.match(/^\/api\/v1\/admin\/stories\/([^/]+)\/chapters\/(\d+)$/);if(m&&req.method==='PUT')return body(req).then(x=>{const c=q('SELECT * FROM chapters WHERE story_id=? AND chapter_index=?',m[1],Number(m[2]));if(!c)return reply(404,{error:'CHAPTER_NOT_FOUND'});const t=now();run('UPDATE chapters SET title=?,content=?,updated_at=?,search_key=? WHERE id=?',String(x.title??c.title).slice(0,200),String(x.content??c.content),t,norm(String(x.title??c.title)),c.id);run('UPDATE stories SET updated_at=? WHERE id=?',t,m[1]);cacheClear('/api/v1/stories');reply(200,chapterRow(q('SELECT * FROM chapters WHERE id=?',c.id)))});
 if(m&&req.method==='DELETE'){const c=q('SELECT * FROM chapters WHERE story_id=? AND chapter_index=?',m[1],Number(m[2]));if(!c)return reply(404,{error:'CHAPTER_NOT_FOUND'});run('DELETE FROM chapters WHERE id=?',c.id);run('UPDATE stories SET updated_at=? WHERE id=?',now(),m[1]);cacheClear('/api/v1/stories');return reply(200,{ok:true})}
 m=p.match(/^\/api\/v1\/admin\/stories\/([^/]+)\/cover$/);if(m&&req.method==='POST')return body(req,7*1024*1024).then(x=>{const s=getStory(m[1]);if(!s)return reply(404,{error:'BOOK_NOT_FOUND'});const data=String(x.data||''),mm=data.match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/);if(!mm)return reply(400,{error:'INVALID_IMAGE'});const ext=mm[1]==='jpeg'?'jpg':mm[1],name=`${s.id}.${ext}`,buf=Buffer.from(mm[2],'base64');if(buf.length>5*1024*1024)return reply(413,{error:'IMAGE_TOO_LARGE'});for(const f of fs.readdirSync(COVERS).filter(f=>f.startsWith(s.id+'.')))fs.unlinkSync(path.join(COVERS,f));fs.writeFileSync(path.join(COVERS,name),buf);const rel='/covers/'+name;run('UPDATE stories SET cover_path=?,updated_at=? WHERE id=?',rel,now(),s.id);cacheClear('/api/v1/stories');reply(200,{cover:rel})}).catch(e=>reply(e.message==='BODY_TOO_LARGE'?413:400,{error:e.message||'BAD_JSON'}));

 if(p==='/api/v1/admin/import/preview'&&req.method==='POST')return body(req,25*1024*1024).then(x=>{try{const d=parseImportFile(String(x.filename||'truyen.txt'),x.data);const seen=new Set(),dupes=[],missing=[];for(const c of d.chapters){if(seen.has(c.num))dupes.push(c.title);if(c.num!=null)seen.add(c.num)}const nums=[...seen].sort((a,b)=>a-b);if(nums.length){for(let n=nums[0];n<=nums[nums.length-1];n++)if(!seen.has(n))missing.push(n)}reply(200,{format:d.format,title:d.title,author:d.author,bytes:d.bytes,total:d.chapters.length,duplicates:dupes,missing,chapters:d.chapters.slice(0,500).map((c,i)=>({index:i,title:c.title,contentLength:c.content.length,num:c.num}))})}catch(e){reply(400,{error:'IMPORT_PARSE_FAILED',detail:e.message})}}).catch(e=>reply(e.message==='BODY_TOO_LARGE'?413:400,{error:e.message||'BAD_JSON'}));
 if(p==='/api/v1/admin/import/commit'&&req.method==='POST')return body(req,25*1024*1024).then(x=>{try{const d=parseImportFile(String(x.filename||'truyen.txt'),x.data);if(!d.chapters.length)return reply(400,{error:'NO_CHAPTERS'});const t=now(),id='b_'+token().slice(0,8),title=String(x.title||d.title||'Truyện nhập').slice(0,200),author=String(x.author||d.author||'').slice(0,120),cat=String(x.cat||'Khác').slice(0,80),desc=String(x.desc||'').slice(0,2000);const seen=new Set(),nums=[];for(const c of d.chapters){if(c.num!=null){if(seen.has(c.num)&&!x.allowIssues)return reply(400,{error:'DUPLICATE_CHAPTER_NUMBER',chapter:c.num});seen.add(c.num);nums.push(c.num)}}if(nums.length&&!x.allowIssues){const min=Math.min(...nums),max=Math.max(...nums),missing=[];for(let n=min;n<=max;n++)if(!seen.has(n))missing.push(n);if(missing.length)return reply(400,{error:'MISSING_CHAPTER_NUMBER',chapters:missing.slice(0,50)})}db.exec('BEGIN IMMEDIATE');run('INSERT INTO stories VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,title,author,cat,desc,norm([title,author,cat,desc].join(' ')),String(x.tone||'').slice(0,200),'FULL','',t,t);for(let i=0;i<d.chapters.length;i++){const c=d.chapters[i];run('INSERT INTO chapters(id,story_id,chapter_index,title,content,created_at,updated_at,search_key) VALUES(?,?,?,?,?,?,?,?)',`${id}:${i}`,id,i,String(c.title||`Chương ${i+1}`).slice(0,200),c.content||'',t,t,norm(String(c.title||`Chương ${i+1}`)))}run('UPDATE stories SET updated_at=? WHERE id=?',now(),id);db.exec('COMMIT');reply(201,{ok:true,story:storyRow(getStory(id)),imported:d.chapters.length,format:d.format})}catch(e){try{db.exec('ROLLBACK')}catch{}reply(400,{error:'IMPORT_COMMIT_FAILED',detail:e.message})}}).catch(e=>reply(e.message==='BODY_TOO_LARGE'?413:400,{error:e.message||'BAD_JSON'}));
 
if(p==='/api/v1/admin/import/jobs'&&req.method==='GET'){
  const u=requireAdmin(req,res);if(!u)return;
  const limit=Math.max(1,Math.min(100,Number(url.parse(req.url,true).query.limit||20)));
  return reply(200,{jobs:all('SELECT * FROM import_jobs ORDER BY updated_at DESC LIMIT ?',limit)});
}
if(p==='/api/v1/admin/import/batch'&&req.method==='POST')return body(req,30*1024*1024).then(x=>{
  const u=requireAdmin(req,res); if(!u)return;
  try{
    const d=parseImportFile(String(x.filename||'truyen.txt'),x.data);
    const batchSize=Math.max(1,Math.min(500,Number(x.batchSize||100)));
    const id='b_'+token().slice(0,8), t=now(), jobId='job_'+token().slice(0,10);
    const title=String(x.title||d.title||'Truyện nhập').slice(0,200),author=String(x.author||d.author||'').slice(0,120),cat=String(x.cat||'Khác').slice(0,80),desc=String(x.desc||'').slice(0,2000);
    const chapters=d.chapters||[]; if(chapters.length>50000)return reply(413,{error:'IMPORT_TOO_LARGE',maxChapters:50000}); run('INSERT INTO import_jobs(id,story_id,filename,status,processed,total,batch_size,error,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)',jobId,id,String(x.filename||'truyen.txt').slice(0,255),'VALIDATING',0,chapters.length,batchSize,'',t,t); const seen=new Set(), duplicates=[], nums=[];
    for(const c of chapters){ if(c.num!=null){if(seen.has(c.num))duplicates.push(c.num); seen.add(c.num); nums.push(c.num);} }
    const min=nums.length?Math.min(...nums):null,max=nums.length?Math.max(...nums):null,missing=[];
    if(min!=null) for(let n=min;n<=max;n++) if(!seen.has(n)) missing.push(n);
    const issues={duplicates:[...new Set(duplicates)],missing,empty:[],short:[],contentDuplicates:[]};
    const contentSeen=new Map(); chapters.forEach((c,i)=>{const len=(c.content||'').trim().length;if(!len)issues.empty.push(i+1);else if(len<50)issues.short.push(i+1);const key=norm(c.content||'').replace(/\s+/g,' ');if(key){if(contentSeen.has(key))issues.contentDuplicates.push([contentSeen.get(key),i+1]);else contentSeen.set(key,i+1)}});
    if((issues.duplicates.length||issues.missing.length||issues.empty.length||issues.short.length||issues.contentDuplicates.length)&&!x.allowIssues){run('UPDATE import_jobs SET status=?,error=?,updated_at=? WHERE id=?','REJECTED','IMPORT_ISSUES',now(),jobId);return reply(400,{error:'IMPORT_ISSUES',issues,checked:chapters.length,jobId});}
    db.exec('BEGIN IMMEDIATE');
    try{
      run('UPDATE import_jobs SET status=?,updated_at=? WHERE id=?','IMPORTING',now(),jobId);
      run('INSERT INTO stories VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,title,author,cat,desc,norm([title,author,cat,desc].join(' ')),String(x.tone||'').slice(0,200),'FULL','',t,t);
      let done=0;
      for(let start=0;start<chapters.length;start+=batchSize){
        for(let i=start;i<Math.min(start+batchSize,chapters.length);i++){const c=chapters[i];run('INSERT INTO chapters(id,story_id,chapter_index,title,content,created_at,updated_at,search_key) VALUES(?,?,?,?,?,?,?,?)',`${id}:${i}`,id,i,String(c.title||`Chương ${i+1}`).slice(0,200),c.content||'',t,t,norm(String(c.title||`Chương ${i+1}`)));done++;}
        run('UPDATE import_jobs SET processed=?,updated_at=? WHERE id=?',done,now(),jobId);}
      run('UPDATE stories SET updated_at=? WHERE id=?',now(),id); db.exec('COMMIT'); run('UPDATE import_jobs SET status=?,processed=?,updated_at=? WHERE id=?','COMPLETED',done,now(),jobId);
      return reply(201,{ok:true,jobId,story:storyRow(getStory(id)),imported:done,batchSize,issues});
    }catch(e){try{db.exec('ROLLBACK')}catch{};run('UPDATE import_jobs SET status=?,error=?,updated_at=? WHERE id=?','FAILED',String(e.message||'IMPORT_ROLLBACK').slice(0,500),now(),jobId);return reply(400,{error:'IMPORT_ROLLBACK',detail:e.message,jobId})}
  }catch(e){return reply(400,{error:'IMPORT_BATCH_FAILED',detail:e.message})}
}).catch(e=>reply(e.message==='BODY_TOO_LARGE'?413:400,{error:e.message||'BAD_JSON'}));
if(p==='/api/v1/admin/stories/diagnostics'&&req.method==='GET'){
  const u=requireAdmin(req,res);if(!u)return; const out=[];
  for(const s of all('SELECT id,title FROM stories ORDER BY title')){
    const rows=all('SELECT chapter_index,title,content FROM chapters WHERE story_id=? ORDER BY chapter_index',s.id), nums=rows.map(r=>Number(r.chapter_index));
    const dup=[],seen=new Set();for(const n of nums){if(seen.has(n))dup.push(n);seen.add(n)};const missing=[];if(nums.length)for(let n=Math.min(...nums);n<=Math.max(...nums);n++)if(!seen.has(n))missing.push(n);
    const empty=rows.filter(r=>!(r.content||'').trim()).map(r=>r.chapter_index),short=rows.filter(r=>(r.content||'').trim().length>0&&(r.content||'').trim().length<50).map(r=>r.chapter_index);
    const cm=new Map(),contentDup=[];rows.forEach(r=>{const k=norm(r.content||'').replace(/\s+/g,' ');if(k){if(cm.has(k))contentDup.push([cm.get(k),r.chapter_index]);else cm.set(k,r.chapter_index)}});
    out.push({id:s.id,title:s.title,total:rows.length,duplicates:[...new Set(dup)],missing,empty,short,contentDuplicates:contentDup});
  } return reply(200,{stories:out});
}
if((m=p.match(/^\/api\/v1\/admin\/stories\/([^/]+)\/renumber$/))&&req.method==='POST')return body(req).then(x=>{const u=requireAdmin(req,res);if(!u)return;const s=getStory(m[1]);if(!s)return reply(404,{error:'BOOK_NOT_FOUND'});const start=Math.max(1,Number(x.start||1));const rows=all('SELECT * FROM chapters WHERE story_id=? ORDER BY chapter_index',s.id);db.exec('BEGIN');try{for(let i=0;i<rows.length;i++)run('UPDATE chapters SET chapter_index=?,id=?,updated_at=? WHERE story_id=? AND chapter_index=?',1000000+i,`${s.id}:tmp:${i}`,now(),s.id,rows[i].chapter_index);for(let i=0;i<rows.length;i++)run('UPDATE chapters SET chapter_index=?,id=?,updated_at=? WHERE story_id=? AND id=?',start+i,`${s.id}:${start+i}`,now(),s.id,`${s.id}:tmp:${i}`);db.exec('COMMIT');cacheClear('/api/v1/stories');reply(200,{ok:true,count:rows.length,start})}catch(e){db.exec('ROLLBACK');reply(400,{error:'RENUMBER_FAILED',detail:e.message})}}).catch(()=>reply(400,{error:'BAD_JSON'}));
if(p==='/api/v1/admin/backup'&&req.method==='GET'){const covers={};for(const f of fs.readdirSync(COVERS)){const fp=path.join(COVERS,f);if(fs.statSync(fp).isFile())covers[f]='data:'+mime(fp).split(';')[0]+';base64,'+fs.readFileSync(fp).toString('base64')}const snap={version:'1.6.1',createdAt:now(),users:all('SELECT * FROM users'),profiles:all('SELECT * FROM profiles'),stories:all('SELECT * FROM stories'),chapters:all('SELECT * FROM chapters'),progress:all('SELECT * FROM reading_progress'),history:all('SELECT * FROM reading_history'),favorites:all('SELECT * FROM favorites'),covers};return reply(200,snap)}
 if(p==='/api/v1/admin/backup/restore'&&req.method==='POST')return body(req,30*1024*1024).then(x=>{if(!Array.isArray(x.stories)||!Array.isArray(x.chapters)||!Array.isArray(x.users))return reply(400,{error:'INVALID_BACKUP'});db.exec('BEGIN');try{db.exec('DELETE FROM favorites; DELETE FROM reading_history; DELETE FROM reading_progress; DELETE FROM chapters; DELETE FROM stories; DELETE FROM profiles; DELETE FROM sessions; DELETE FROM users;');for(const r of x.users)run('INSERT INTO users VALUES(?,?,?,?,?,?,?)',r.id,r.username,r.password_hash,r.password_salt,r.display_name,r.role,r.created_at);for(const r of (x.profiles||[]))run('INSERT INTO profiles VALUES(?,?,?)',r.user_id,r.avatar||'',r.updated_at||now());for(const r of x.stories)run('INSERT INTO stories VALUES(?,?,?,?,?,?,?,?,?,?,?)',r.id,r.title,r.author,r.category,r.description,r.search_key||norm([r.title,r.author,r.category,r.description].join(' ')),r.tone,r.status,r.cover_path||'',r.created_at,r.updated_at);for(const r of x.chapters)run('INSERT INTO chapters(id,story_id,chapter_index,title,content,created_at,updated_at,search_key) VALUES(?,?,?,?,?,?,?,?)',r.id,r.story_id,r.chapter_index,r.title,r.content,r.created_at,r.updated_at);for(const r of (x.progress||[]))run('INSERT INTO reading_progress VALUES(?,?,?,?,?)',r.user_id,r.story_id,r.chapter_index,r.position,r.updated_at);for(const r of (x.history||[]))run('INSERT INTO reading_history VALUES(?,?,?,?,?)',r.user_id,r.story_id,r.chapter_index,r.position,r.updated_at);for(const r of (x.favorites||[]))run('INSERT INTO favorites VALUES(?,?,?)',r.user_id,r.story_id,r.created_at);db.exec('COMMIT');for(const f of fs.readdirSync(COVERS))fs.unlinkSync(path.join(COVERS,f));for(const [name,data] of Object.entries(x.covers||{})){const mm=String(data).match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/);if(mm)fs.writeFileSync(path.join(COVERS,path.basename(name)),Buffer.from(mm[2],'base64'))}reply(200,{ok:true})}catch(e){db.exec('ROLLBACK');reply(400,{error:'RESTORE_FAILED',detail:e.message})}}).catch(()=>reply(400,{error:'BAD_JSON'}));
}
if(p.startsWith('/covers/')){const f=path.join(COVERS,path.basename(p));if(fs.existsSync(f))return reply(200,fs.readFileSync(f),mime(f))}
if(p==='/'||p==='/index.html'){const f=path.join(ROOT,'index.html');return reply(200,fs.readFileSync(f,'utf8'),'text/html; charset=utf-8')}
const file=path.normalize(path.join(ROOT,p));if(file.startsWith(ROOT)&&fs.existsSync(file)&&fs.statSync(file).isFile()){const ext=path.extname(file);const types={'.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.html':'text/html; charset=utf-8'};return reply(200,fs.readFileSync(file),types[ext]||'application/octet-stream')}return reply(404,{error:'NOT_FOUND'})}

function zipEntries(buf){
  const out=[]; let eocd=-1;
  for(let i=buf.length-22;i>=Math.max(0,buf.length-65557);i--){if(buf.readUInt32LE(i)===0x06054b50){eocd=i;break}}
  if(eocd<0)throw new Error('INVALID_ZIP');
  const n=buf.readUInt16LE(eocd+10),cd=buf.readUInt32LE(eocd+12),off=buf.readUInt32LE(eocd+16);let p=off;
  for(let i=0;i<n;i++){if(buf.readUInt32LE(p)!==0x02014b50)throw new Error('INVALID_ZIP_CENTRAL');const method=buf.readUInt16LE(p+10),csize=buf.readUInt32LE(p+20),usize=buf.readUInt32LE(p+24),nl=buf.readUInt16LE(p+28),el=buf.readUInt16LE(p+30),cl=buf.readUInt16LE(p+32),lo=buf.readUInt32LE(p+42);const name=buf.slice(p+46,p+46+nl).toString('utf8');out.push({name,method,csize,usize,lo});p+=46+nl+el+cl}
  return out;
}
function zipRead(buf,e){const p=e.lo;if(buf.readUInt32LE(p)!==0x04034b50)throw new Error('INVALID_ZIP_LOCAL');const nl=buf.readUInt16LE(p+26),el=buf.readUInt16LE(p+28),data=buf.slice(p+30+nl+el,p+30+nl+el+e.csize);if(e.method===0)return data;if(e.method===8)return zlib.inflateRawSync(data);throw new Error('UNSUPPORTED_ZIP_COMPRESSION')}
function stripHtml(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?>/gi,'\n').replace(/<\/p\s*>/gi,'\n').replace(/<\/div\s*>/gi,'\n').replace(/<\/h[1-6]\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#39;/g,"'").replace(/&quot;/gi,'"').replace(/\r/g,'').replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
function chapterizeText(text){
  const lines=String(text||'').replace(/^\uFEFF/,'').split(/\n/), re=/^\s*(?:chương|chuong|chapter|chap(?:ter)?|hồi|hoi)\s*(?:[.:#-]?\s*)?(\d+)?(?:\s*[:.\-–—]\s*|\s+)?(.{0,180})\s*$/i;let starts=[];
  lines.forEach((line,i)=>{const m=line.match(re);if(m&&((m[1]!==undefined)||/chương|chuong|chapter|hồi|hoi/i.test(line)))starts.push({line:i,num:m[1]?Number(m[1]):null,title:(m[2]||'').trim()})});
  if(starts.length===0)return [{index:0,title:'Chương 1',content:String(text||'').trim(),num:null}];
  if(starts.length===1){const a=starts[0],title=a.title||`Chương ${a.num??1}`,content=lines.slice(a.line+1).join('\n').trim();return [{index:0,title,content,num:a.num}]}
  const out=[];for(let i=0;i<starts.length;i++){const a=starts[i],b=starts[i+1]?.line??lines.length;let title=a.title||`Chương ${a.num??i+1}`;let content=lines.slice(a.line+1,b).join('\n').trim();out.push({index:i,title,content,num:a.num})}return out;
}
function parseEpub(buf){
  const es=zipEntries(buf),map=new Map(es.map(e=>[e.name,e]));const readName=n=>{const e=map.get(n);return e?zipRead(buf,e).toString('utf8'):''};const container=readName('META-INF/container.xml');const opfMatch=container.match(/full-path\s*=\s*["']([^"']+)["']/i);if(!opfMatch)throw new Error('EPUB_NO_OPF');const opfPath=opfMatch[1],base=path.posix.dirname(opfPath),opf=readName(opfPath);if(!opf)throw new Error('EPUB_OPF_READ');
  const title=(opf.match(/<dc:title[^>]*>([\s\S]*?)<\/dc:title>/i)||[])[1]||'';const author=(opf.match(/<dc:creator[^>]*>([\s\S]*?)<\/dc:creator>/i)||[])[1]||'';const manifest={};for(const m of opf.matchAll(/<item\b[^>]*id=["']([^"']+)["'][^>]*href=["']([^"']+)["'][^>]*media-type=["']([^"']+)["'][^>]*>/gi))manifest[m[1]]={href:m[2],type:m[3]};const spine=[];for(const m of opf.matchAll(/<itemref\b[^>]*idref=["']([^"']+)["'][^>]*>/gi)){if(manifest[m[1]])spine.push(manifest[m[1]])}
  const chapters=[];for(const it of spine){if(!/html|xhtml/i.test(it.type))continue;const name=path.posix.normalize(path.posix.join(base,it.href));const raw=readName(name);if(!raw)continue;const txt=stripHtml(raw);if(!txt)continue;const local=chapterizeText(txt);for(const c of local)chapters.push(c)}return {title:stripHtml(title),author:stripHtml(author),chapters:chapters.map((c,i)=>({...c,index:i,title:c.title||`Chương ${i+1}`}))};
}
function parseImportFile(filename,data){const ext=path.extname(filename||'').toLowerCase(),buf=Buffer.from(String(data||'').replace(/^data:[^;]+;base64,/,'').trim(),'base64');if(!buf.length)throw new Error('EMPTY_FILE');if(buf.length>20*1024*1024)throw new Error('IMPORT_TOO_LARGE');if(ext==='.epub'||buf.readUInt32LE(0)===0x04034b50){const e=parseEpub(buf);return {...e,format:'epub',bytes:buf.length}}const text=buf.toString('utf8').replace(/\u0000/g,'');return {title:path.basename(filename||'Truyện',ext).replace(/[_-]+/g,' ').trim(),author:'',chapters:chapterizeText(text),format:'txt',bytes:buf.length};}

function mime(f){return {'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp'}[path.extname(f).toLowerCase()]||'application/octet-stream'}
const server=http.createServer((req,res)=>{try{route(req,res)}catch(e){console.error(e);if(!res.headersSent)send(res,500,{error:'INTERNAL_ERROR',detail:e.message},'application/json; charset=utf-8',req)}});server.listen(PORT,()=>console.log(`Kho Truyen API v1.6.1 http://localhost:${PORT}`));
process.on('SIGINT',()=>{db.close();server.close(()=>process.exit(0))});process.on('SIGTERM',()=>{db.close();server.close(()=>process.exit(0))});
